[[constraint]]
  branch = "master"
  name = "github.com/cloudfoundry-community/go-cfclient"

[[constraint]]
  name = "github.com/cloudfoundry-community/go-cfenv"
  version = "1.17.0"

[[constraint]]
  name = "github.com/govau/cf-common"
  version = "0.0.7"

[prune]
  go-tests = true
  unused-packages = true
