---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: govau/cga-cf-bosh-cli
    tag: latest

inputs:
- name: ci
- name: src
- name: img
- name: log-proxy-src
- name: log-proxy-img
- name: es-proxy-src
- name: es-proxy-img

outputs: []

params:
  ENV:
  KUBECONFIG:

run:
  path: ci/ci/build.sh
